### ISSUE TITLE
"Processor Definition" is probably missing

### ISSUE THREAD

**Issue by AngelaMariaDespotopoulou** [datacrop/maize-digital-models#6]
DataManagement.xsd:

PO -- DataProcessors -- PM -- processorDefinitionReferenceID

Shouldn't we have an entity "Processor Definition" as well?

**Comment by nkef** [comment]
There is an entity P[rocessor Definition (PD) ](https://github.com/datacrop/maize-digital-models/blob/d2efa504ee874af103b012ef52dc9d83eb3b7b84/schemata/core/DataCROP-DataManagement.xsd#L343)available at the schema.
